api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor