services:
    user_listener:
        class: AppBundle\Listeners\UserEventListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]

    registration_listener:
        class: AppBundle\Listeners\RegistrationListener
        tags:
            - { name: kernel.event_subscriber }

    doctrine_listener:
        class: AppBundle\Listeners\DoctrineSubscriber
        tags:
            - { name: doctrine.event_subscriber}

    kernel_listeners:
        class: AppBundle\Listeners\KernelException
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}

    app_collector:
        class: AppBundle\Collector\RequestCollector
        tags:
            - { name: data_collector}